from datetime import datetime
from uuid import UUID

from pydantic import (
    BaseModel,
    ConfigDict,
    EmailStr,
    Field,
    field_validator,
)


class UserCreate(BaseModel):
    """
    Request schema used to synchronize a Clerk user.

    The database UUID is generated by SQLAlchemy.
    The Clerk user ID is extracted from the verified Clerk token.
    """

    model_config = ConfigDict(
        str_strip_whitespace=True,
    )

    name: str = Field(
        min_length=2,
        max_length=100,
    )

    email: EmailStr

    @field_validator("name")
    @classmethod
    def validate_name(cls, value: str) -> str:
        """Ensure the user's name contains meaningful characters."""

        if not value:
            raise ValueError("Name cannot be empty.")

        return value

    @field_validator("email")
    @classmethod
    def normalize_email(cls, value: EmailStr) -> str:
        """Convert the email address to lowercase."""

        return str(value).lower()


class UserResponse(BaseModel):
    """Response schema returned for a database user."""

    model_config = ConfigDict(
        from_attributes=True,
    )

    id: UUID
    clerk_id: str
    name: str
    email: EmailStr
    created_at: datetime
    updated_at: datetime


class TokenResponse(BaseModel):
    """Response schema returned after successful authentication."""

    access_token: str
    token_type: str